version: "3.5"  # optional since v1.27.0
services:
  nginx:
    networks:
      - inception_network
    image: nginx
    depends_on:
      - wordpress
      - mariadb
    container_name: nginx
    build: ./requirements/nginx/
    ports:
      - 443:443
    volumes:
      - myapp:/var/www/html

  mariadb:
    networks:
      - inception_network
    image: mariadb
    container_name: mariadb
    build: ./requirements/mariadb/
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql

  wordpress:
    networks:
      - inception_network
    image: wordpress
    # restart: always
    container_name: wordpress
    depends_on:
      - mariadb
    build: ./requirements/wordpress/
    ports:
      - 9000:9000
    volumes:
      - myapp:/var/www/html/
    env_file:
      - .env

  adminer:
    networks:
      - inception_network
    image: adminer
    container_name: adminer
    depends_on:
      - mariadb
    ports:
      - 8080:80
    build: ./requirements/bonus/adminer/
    env_file:
      - .env

  # gitlab:
  #   networks:
  #     - inception_network
  #   image: gitlab
  #   build: ./requirements/bonus/gitlab/
  #   container_name: gitlab
  #   ports:
  #     - "9987:9987"
  #     - "10011:10011"
  #     - "30033:30033"
  #   environment:
  #     - GITLAB_ROOT_PASSWORD=root

  # website:
  #   networks:
  #     - inception_network
  #   image: website
  #   build: 
  #     context: ./requirements/bonus/website/
  #     args:
  #       GITHUB_TOKEN:

  #   container_name: website
  #   ports:
  #     - 3000:3000
  
  ftp:
    depends_on:
      - wordpress
    networks:
      - inception_network
    image: ftp
    build: 
      context: ./requirements/bonus/ftp/
    volumes:
      - myapp:/home/tin/ftp/files
    container_name: ftp
    ports:
      - "20:20"
      - "21:21"

  redis:
    depends_on:
      - wordpress
    networks:
      - inception_network
    image: redis
    container_name: redis
    build: ./requirements/bonus/redis/
    ports:
      - 6379:6379

volumes:
  db:
  myapp:

networks:
  inception_network:
      name: 'inception_network'
      driver: bridge
